[config]
default_to_workspace = false

# In native mode we need to build in wasm32-wasi
# Because of getrandom crate which has different implementations
# Between wasi which has no browser and wasm
# https://docs.rs/getrandom/latest/getrandom/

[tasks.simple-mod-wasi]
command = "cargo"
args = [
    "build",
    "--profile",
    "release-wasm",
    "--package",
    "simple_mod",
    "--target",
    "wasm32-wasi",
]

[tasks.simple-mod-wasi-copy]
script_runner = "@shell"
script = '''
cp "target/wasm32-wasi/release-wasm/deps/simple_mod.wasm", "examples/simple/simple/assets/simple_mod.wasm"
'''

[tasks.run-simple]
command = "cargo"
args = ["run", "--bin", "simple"]
dependencies = ["simple-mod-wasi", "simple-mod-wasi-copy"]

[tasks.simple-mod-wasm]
command = "cargo"
args = [
    "build",
    "--profile",
    "release-wasm",
    "--package",
    "simple_mod",
    "--target",
    "wasm32-unknown-unknown",
]

[tasks.simple-mod-wasm-copy]
script_runner = "@shell"
script = '''
cp "target/wasm32-unknown-unknown/release-wasm/simple_mod.wasm", "examples/simple/simple/assets/simple_mod.wasm"
'''

[tasks.run-simple-wasm]
command = "cargo"
args = ["run", "--bin", "simple", "--target", "wasm32-unknown-unknown"]
dependencies = ["simple-mod-wasm", "simple-mod-wasm-copy"]

[tasks.cubes-mod-with-bevy-wasi]
command = "cargo"
args = [
    "build",
    "--profile",
    "release-wasm",
    "--package",
    "mod_with_bevy",
    "--target",
    "wasm32-wasi",
]

[tasks.cubes-mod-without-bevy-wasi]
command = "cargo"
args = [
    "build",
    "--profile",
    "release-wasm",
    "--package",
    "mod_without_bevy",
    "--target",
    "wasm32-wasi",
]

[tasks.cubes-mod-wasi-copy]
script_runner = "@shell"
script = '''
cp "target/wasm32-wasi/release-wasm/deps/mod_with_bevy.wasm", "examples/cubes/cubes/assets/mod_with_bevy.wasm"
cp "target/wasm32-wasi/release-wasm/deps/mod_without_bevy.wasm", "examples/cubes/cubes/assets/mod_without_bevy.wasm"
'''

[tasks.run-cubes]
command = "cargo"
args = ["run", "--bin", "cubes"]
dependencies = [
    "cubes-mod-with-bevy-wasi",
    "cubes-mod-without-bevy-wasi",
    "cubes-mod-wasi-copy",
]

[tasks.cubes-mod-with-bevy-wasm]
command = "cargo"
args = [
    "build",
    "--profile",
    "release-wasm",
    "--package",
    "mod_with_bevy",
    "--target",
    "wasm32-unknown-unknown",
]

[tasks.cubes-mod-without-bevy-wasm]
command = "cargo"
args = [
    "build",
    "--profile",
    "release-wasm",
    "--package",
    "mod_without_bevy",
    "--target",
    "wasm32-unknown-unknown",
]

[tasks.cubes-mod-wasm-copy]
script_runner = "@shell"
script = '''
cp "target/wasm32-unknown-unknown/release-wasm/deps/mod_with_bevy.wasm", "examples/cubes/cubes/assets/mod_with_bevy.wasm"
cp "target/wasm32-unknown-unknown/release-wasm/deps/mod_without_bevy.wasm", "examples/cubes/cubes/assets/mod_without_bevy.wasm"
'''

[tasks.run-cubes-wasm]
command = "cargo"
args = ["run", "--bin", "cubes", "--target", "wasm32-unknown-unknown"]
dependencies = [
    "cubes-mod-with-bevy-wasm",
    "cubes-mod-without-bevy-wasm",
    "cubes-mod-wasm-copy",
]

[tasks.shared-resources-mod-wasi]
command = "cargo"
args = [
    "build",
    "--profile",
    "release-wasm",
    "--package",
    "shared_resources_mod",
    "--target",
    "wasm32-wasi",
]

[tasks.shared-resources-mod-wasi-copy]
script_runner = "@shell"
script = '''
cp "target/wasm32-wasi/release-wasm/deps/shared_resources_mod.wasm", "examples/shared_resources/shared_resources/assets/shared_resources_mod.wasm"
'''

[tasks.run-shared-resources]
command = "cargo"
args = ["run", "--bin", "shared_resources"]
dependencies = ["shared-resources-mod-wasi", "shared-resources-mod-wasi-copy"]

[tasks.shared-resources-mod-wasm]
command = "cargo"
args = [
    "build",
    "--profile",
    "release-wasm",
    "--package",
    "shared_resources_mod",
    "--target",
    "wasm32-unknown-unknown",
]

[tasks.shared-resources-mod-wasm-copy]
script_runner = "@shell"
script = '''
cp "target/wasm32-unknown-unknown/release-wasm/shared_resources_mod.wasm", "examples/shared_resources/shared_resources/assets/shared_resources_mod.wasm"
'''

[tasks.run-shared-resources-wasm]
command = "cargo"
args = [
    "run",
    "--bin",
    "shared_resources",
    "--target",
    "wasm32-unknown-unknown",
]
dependencies = ["shared-resources-mod-wasm", "shared-resources-mod-wasm-copy"]
